LOCAL_ARM_MODE := arm
LOCAL_C_INCLUDES := $(DOG_SRC_MAIN)/common $(DOG_SRC_MAIN)/public $(DOG_C_INCLUDES)
LOCAL_CFLAGS := -D_LINUX -O2 $(DOG_CFLAGS)
LOCAL_LDFLAGS := $(DOG_LDFLAGS)
LOCAL_LDLIBS := $(DOG_LDLIBS)
LOCAL_SRC_FILES := $(DOG_SRC_FILES)
ifeq ($(DOG_STATIC_LIBRARY), true)
include $(BUILD_STATIC_LIBRARY)
else
include $(BUILD_SHARED_LIBRARY)
endif