DOG_C_INCLUDES := \
  "$(DOG_SRC_MAIN)/public/tier0" \
  "$(DOG_SRC_MAIN)/public/tier1"
DOG_SRC_FILES := \
  vgui2/vgui_controls/AnalogBar.cpp \
  vgui2/vgui_controls/AnimatingImagePanel.cpp \
  vgui2/vgui_controls/AnimationController.cpp \
  vgui2/vgui_controls/BitmapImagePanel.cpp \
  vgui2/vgui_controls/BuildFactoryHelper.cpp \
  vgui2/vgui_controls/BuildGroup.cpp \
  vgui2/vgui_controls/BuildModeDialog.cpp \
  vgui2/vgui_controls/Button.cpp \
  vgui2/vgui_controls/CheckButton.cpp \
  vgui2/vgui_controls/CheckButtonList.cpp \
  vgui2/vgui_controls/CircularProgressBar.cpp \
  vgui2/vgui_controls/ComboBox.cpp \
  vgui2/vgui_controls/consoledialog.cpp \
  vgui2/vgui_controls/ControllerMap.cpp \
  vgui2/vgui_controls/controls.cpp \
  vgui2/vgui_controls/DirectorySelectDialog.cpp \
  vgui2/vgui_controls/Divider.cpp \
  vgui2/vgui_controls/EditablePanel.cpp \
  vgui2/vgui_controls/ExpandButton.cpp \
  vgui2/vgui_controls/FileOpenDialog.cpp \
  vgui2/vgui_controls/FileOpenStateMachine.cpp \
  vgui2/vgui_controls/FocusNavGroup.cpp \
  vgui2/vgui_controls/Frame.cpp \
  vgui2/vgui_controls/GraphPanel.cpp \
  vgui2/vgui_controls/Image.cpp \
  vgui2/vgui_controls/ImageList.cpp \
  vgui2/vgui_controls/ImagePanel.cpp \
  vgui2/vgui_controls/InputDialog.cpp \
  vgui2/vgui_controls/KeyBindingHelpDialog.cpp \
  vgui2/vgui_controls/KeyBoardEditorDialog.cpp \
  vgui2/vgui_controls/KeyRepeat.cpp \
  vgui2/vgui_controls/Label.cpp \
  vgui2/vgui_controls/ListPanel.cpp \
  vgui2/vgui_controls/ListViewPanel.cpp \
  vgui2/vgui_controls/Menu.cpp \
  vgui2/vgui_controls/MenuBar.cpp \
  vgui2/vgui_controls/MenuButton.cpp \
  vgui2/vgui_controls/MenuItem.cpp \
  vgui2/vgui_controls/MessageBox.cpp \
  vgui2/vgui_controls/MessageDialog.cpp \
  vgui2/vgui_controls/Panel.cpp \
  vgui2/vgui_controls/PanelListPanel.cpp \
  vgui2/vgui_controls/ProgressBar.cpp \
  vgui2/vgui_controls/ProgressBox.cpp \
  vgui2/vgui_controls/PropertyDialog.cpp \
  vgui2/vgui_controls/PropertyPage.cpp \
  vgui2/vgui_controls/PropertySheet.cpp \
  vgui2/vgui_controls/QueryBox.cpp \
  vgui2/vgui_controls/RadioButton.cpp \
  vgui2/vgui_controls/RichText.cpp \
  vgui2/vgui_controls/RotatingProgressBar.cpp \
  vgui2/vgui_controls/savedocumentquery.cpp \
  vgui2/vgui_controls/ScrollableEditablePanel.cpp \
  vgui2/vgui_controls/ScrollBar.cpp \
  vgui2/vgui_controls/ScrollBarSlider.cpp \
  vgui2/vgui_controls/SectionedListPanel.cpp \
  vgui2/vgui_controls/Slider.cpp \
  vgui2/vgui_controls/Splitter.cpp \
  vgui2/vgui_controls/subrectimage.cpp \
  vgui2/vgui_controls/TextEntry.cpp \
  vgui2/vgui_controls/TextImage.cpp \
  vgui2/vgui_controls/ToggleButton.cpp \
  vgui2/vgui_controls/Tooltip.cpp \
  vgui2/vgui_controls/ToolWindow.cpp \
  vgui2/vgui_controls/TreeView.cpp \
  vgui2/vgui_controls/TreeViewListControl.cpp \
  vgui2/vgui_controls/URLLabel.cpp \
  vgui2/vgui_controls/WizardPanel.cpp \
  vgui2/vgui_controls/WizardSubPanel.cpp
DOG_STATIC_LIBRARY := true